---
title: "Bibliography"
author: "Aarav Vishesh Dewangan"
date: "07/03/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Acknowledgements:

Kaggle, Mauna Loa Observatory, Wang Q, Taylor JE (2016) Patterns and limitations of urban human mobility resilience under the influence of multiple types of natural disaster, Dryad digital repository and any scientist that helped us collect this data.

## References:

- [Benevolenza, M., DeRigne, L. (2018). The impact of climate change and natural disasters on vulnerable populations: A systematic review of literature, 29(2), 266-281](https://www.tandfonline.com/doi/abs/10.1080/10911359.2018.1527739)

- D'Ignazio C, Klein LF. Data Feminism. Cambridge, MA: The MIT Press; 2020.

- [Kane, S., Reilly, J., & Tobey, J. (1992). An empirical study of the economic effects of climate change on World Agriculture. Climatic Change, 21(1), 17–35.](https://doi.org/10.1007/bf00143251)

-  [Lindsey, R., & Dahlman, L. A. (2021, August 12). Climate change: Global temperature. Climate Change: Global Temperature | NOAA Climate.gov. Retrieved February 4, 2022,](https://www.climate.gov/news-features/understanding-climate/climate-change-global-temperature#:~:text=According%20to%20NOAAs%202020%20Annual,more%20than%20twice%20that%20rate. )

- [Podesta J. The climate crisis, migration, and refugees. Brookings.](https://www.brookings.edu/research/the-climate-crisis-migration-and-refugees. Published July 1,2021. Accessed February 4,2022. )

- [Rights and Resources. Toward a global baseline of carbon storage in collective lands: An updated analysis of Indigenous Peoples' and local communities' contributions to climate change mitigation. Rights + Resources.](https://rightsandresources.org/global-baseline-carbon-storage-collective-lands/.PublishedMarch16,2020. Accessed February 4,2022.)

- [Ritchie, H., Roser, M. CO₂ and Greenhouse Gas Emissions](https://ourworldindata.org/co2-and-other-greenhouse-gas-emission. Published May, 2017, Accessed March 4, 2022)

- [Vidal J. Climate change will hit poor countries hardest, study shows. The Guardian](https://www.theguardian.com/global-development/2013/sep/27/climate-change-poor-countries-ipcc. Published September 27, 2013. Accessed February 4, 2022. )
