---
title: "Introduction"
author: "Aarav Vishesh Dewangan"
date: "06/03/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Abstract:

This project focuses on the effects and impact of climate change, such as natural disasters. In order to address this, we will comb through existing data to examine the occurrence and frequency of natural disasters. We are concerned with this because climate change is a growing concern with catastrophic impacts such as environmental destruction, displacement, and more. Accordingly, we hope to demonstrate the urgency of climate change and the need for an intervention.

## Keywords:

**Climate change**, **Environment**, **Natural Disaster**

## Introduction:

Our aim with this project is to deal with the topic of climate change and its catastrophic impacts. Climate change has become one of the primary concerns of today’s world. Increased heat, drought, insect outbreak, all interconnected with climate change has brought some of the most dramatic changes like melting of glaciers, forest fires, shifting of plant and animal ranges etc. These changes are very harmful for the environment. So thus climate change is a topic of major concern which needs proper attention of all the people around the globe. Hence our team has chosen to take up this topic to dig up reasons for climate change which can lead to effective solutions. 
Specifically our project will deal with some of the important questions like reasons for climate change, severity and impacts of this issue, degree to which it is impacting our planet earth and lastly the causes of climate change. 
 

## Values and Stakeholders:

Health awareness, responsibility, consideration are the human values that stem from the problem of climate change since dealing with this issue is protecting the future world for our younger generations. Confronting this concern will help us preserve the Earth for the future.

The direct stakeholders of climate change include the farmers and industrial manufacturers. For instance, the gasoline emissions from our vehicles contribute to 1.6 billion tons of greenhouse gasses which further exacerbate the impact of climate change (United States Environmental Protection Agency, 2022). Additionally, the production of hot-commodities such as processed foods, meat and poultry and greenhouse gasses to produce seasonal foods year-round attends to the demands of human lifestyle. Despite the direct impacts of human lifestyle, other aspects of the earth are impacted by climate change. Indirect stakeholders include us, the normal customers when the decrease in food or fuel supply will majorly affect people's daily lives.

## Design Situation

Since the 1880s, the earth's temperature has risen at a rate of at least 0.18 degrees Celsius per decade (Lindsey et al., 2021). With the earth's climate temperature rising significantly, there have been major impacts to all aspects of life. Climate change has been a trending topic of discussion and in the recent decades, there has been increased awareness and effort to prevent further damage to the earth. From the ban on plastic bags and implementation of compost wastebins to the advent of electric cars and solar energy, technology has advanced to combat the negative effects of climate change.

Health awareness, responsibility, consideration are the human values that stem from the problem of climate change since dealing with this issue is protecting the future world for our younger generations. Confronting this concern will help us preserve the Earth for the future.

The direct stakeholders of climate change include the farmers and industrial manufacturers. For instance, the gasoline emissions from our vehicles contribute to 1.6 billion tons of greenhouse gasses which further exacerbate the impact of climate change (United States Environmental Protection Agency, 2022). Additionally, the production of hot-commodities such as processed foods, meat and poultry and greenhouse gasses to produce seasonal foods year-round attends to the demands of human lifestyle. Despite the direct impacts of human lifestyle, other aspects of the earth are impacted by climate change. Indirect stakeholders include us, the normal customers when the decrease in food or fuel supply will majorly affect people's daily lives.

Although climate change has an overwhelming amount of negative effects, some benefits have arisen from it. If tackled with data and technology, we can easily find the gap in our system that leads to climate change in the first place. The usage of technology will enable us to analyze and give effective solutions to the issue. Using technology and data will be more effective in raising the public awareness about the environment, which leads to numerous benefits. For instance, with an increase in climate change awareness, there has been a more competitive job market especially for technology-related careers. This competition in turn will promote more innovation and technological advances. Additionally in the agriculture world, the usage of data will help farmers make decisions based on the climate data. For instance, there has been greater success with crop yields in the northern latitude regions for crops like wheat, barley, and oats that grow better in warmer climates (Kane et al., 1992). However, over-usage or mishandling of data might lead to public confusion due to wrong interpretation of data. Consequently, inappropriate decisions will be made which might cause further damage to the environment.
