---
title: "Summary Statistics"
author: "Aarav Vishesh Dewangan"
date: "08/03/2022"
output: html_document
---



## Summary Statistics of 5 Variables:-


```
## $max_land__avg_temperature
## [1] 21.32
## 
## $min_land__avg_temperature
## [1] 7.229
## 
## $max_land_ocean_temperature
## [1] 17.611
## 
## $min_land_ocean_temperature
## [1] 13.298
## 
## $mean_affected_since_1958
## [1] 880213.9
## 
## $max_co2_level
## [1] 407.65
## 
## $min_co2_level
## [1] 313.21
## 
## $mean_death_since_1958
## [1] 696.9764
```
The 5 variables that we have chosen to dissect the datasets are the following:-

- Land Max Temperature - 

The maximum land temperature  recorded was 21.32 Celsius in 2011, and the minimum
 land temperature was -5.407 Celsius in 1857. 

- Land and Ocean Average Temperature -

The maximum land and ocean average temperature  recorded was 17.611 Celsius in 2015, and the minimum
average land and ocean temperature was 12.475 Celsius in 1857. 

-  Carbon dioxide levels -

The maimum carbon dioxide level was 407.65 ppm in 2016 and the minimum carbon dioxide level was 313.21 ppm in 1958. 

- Average Number of deaths -
 
The mean number of deaths between 1900 and 2021 due to natural disasters is 2842.866. Natural disasters have primarily occurred due to climate change.

- Average Number of Affected people

The average number of affected people between 1900 and 2021 due to natural disasters is 882361.9. Natural disasters have primarily occurred due to climate change.

